version: '3.5'
networks:
  stock-chat-app:
    name: stock-chat-app

services:
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.9
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
    volumes:
      - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'
    networks:
      - stock-chat-app
  
  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      - REDIS_PASSWORD=uU23o#0TU#BtNycSFv
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - stock-chat-app
  
  stock-chat-app-bot:
    build:
      context: .
      dockerfile: src/StockChatApp.Bot/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    networks:
      - stock-chat-app

  stock-chat-app-web:
    build:
      context: .
      dockerfile: src/StockChatApp.Web/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
      - redis
    ports:
      - "5076:80"
      - "7159:443"
    networks:
      - stock-chat-app

volumes:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
